[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0f918b"
backgroundColor = "#e9eff0"
secondaryBackgroundColor = "#fbfcfa"
textColor = "#17272b"
font = "sans serif"
